// Demo report shown when no API key is configured. All businesses are fictional.
export const sampleReport = {
  demo: true,
  generated_at: "2026-09-24T10:00:00.000Z",
  input: { business: "Brew Haven Coffee (demo)", location: "Austin, TX", industry: "Specialty coffee shop", website: "" },
  industry: "Specialty coffee / cafe",
  overall_position: "challenger",
  executive_summary:
    "Brew Haven is a well-reviewed independent cafe competing in a crowded Austin specialty coffee market. Two local chains dominate foot traffic and search visibility, while a national chain wins on convenience and loyalty. Brew Haven leads on product quality and atmosphere but trails on digital presence and has no loyalty program. The biggest openings are remote-worker daytime demand, local SEO for 'coffee near me' searches, and community events that larger rivals don't run.",
  target: {
    name: "Brew Haven Coffee", website: "brewhaven.example", location: "East Austin, TX",
    description: "Independent third-wave cafe with in-house roasting, pastries from a local bakery and a large co-working friendly seating area.",
    price_tier: "mid-range", target_audience: "Young professionals, remote workers, students",
    usp: "Small-batch beans roasted on site; spacious work-friendly seating",
    rating: 4.7, review_count: "~640 Google reviews",
    strengths: ["Highest-rated coffee quality in the area", "Spacious seating and fast Wi-Fi", "On-site roasting story"],
    weaknesses: ["Weak Instagram (posts irregularly)", "No loyalty or mobile ordering", "Limited parking"],
    marketing_channels: ["Google Business Profile", "Instagram", "Word of mouth"],
    scores: { pricing_value: 7, product_quality: 9, brand_strength: 6, digital_presence: 4, customer_experience: 8, innovation: 6 },
  },
  competitors: [
    {
      name: "Lone Star Roasters", website: "lonestarroasters.example", location: "3 locations, Austin", type: "direct",
      description: "Local specialty chain with a strong brand and wholesale bean business.",
      price_tier: "premium", target_audience: "Coffee enthusiasts, tourists", usp: "Award-winning roasts and polished brand",
      rating: 4.6, review_count: "~2,100 Google reviews",
      strengths: ["Strong brand recognition", "Excellent Instagram content", "Retail bean sales online"],
      weaknesses: ["Crowded, limited seating", "Higher prices", "Slow service reviews at peak"],
      marketing_channels: ["Instagram", "E-commerce", "Local press", "Wholesale partnerships"],
      scores: { pricing_value: 5, product_quality: 9, brand_strength: 9, digital_presence: 9, customer_experience: 6, innovation: 7 },
      threat_level: "high", threat_reason: "Dominates local search and social mindshare for 'best coffee Austin'.",
    },
    {
      name: "Daily Grind Cafe", website: "dailygrindatx.example", location: "East Austin, TX", type: "direct",
      description: "Neighborhood cafe two blocks away with brunch menu and late hours.",
      price_tier: "mid-range", target_audience: "Locals, brunch crowd", usp: "Full food menu and open until 10pm",
      rating: 4.4, review_count: "~890 Google reviews",
      strengths: ["Food menu drives larger tickets", "Late hours", "Loyalty punch card"],
      weaknesses: ["Coffee quality rated average", "Noisy — poor for working", "Dated website"],
      marketing_channels: ["Google Business Profile", "Yelp", "Facebook"],
      scores: { pricing_value: 7, product_quality: 6, brand_strength: 6, digital_presence: 5, customer_experience: 7, innovation: 4 },
      threat_level: "medium", threat_reason: "Same neighborhood; competes for the morning and weekend crowd.",
    },
    {
      name: "Starline Coffee Co. (national chain)", website: "starline.example", location: "5 stores within 2 miles", type: "direct",
      description: "National chain with mobile ordering and a large rewards program.",
      price_tier: "mid-range", target_audience: "Commuters, convenience seekers", usp: "Speed, consistency and app rewards",
      rating: 4.0, review_count: "Thousands across locations",
      strengths: ["Mobile order-ahead", "Rewards program", "Drive-thru convenience"],
      weaknesses: ["Generic experience", "Lower perceived quality", "Little local connection"],
      marketing_channels: ["Mobile app", "National TV/digital ads", "Email/push"],
      scores: { pricing_value: 6, product_quality: 5, brand_strength: 10, digital_presence: 10, customer_experience: 6, innovation: 8 },
      threat_level: "medium", threat_reason: "Wins commuters on convenience; less relevant for sit-down customers.",
    },
    {
      name: "The Work Loft", website: "theworkloft.example", location: "Downtown Austin", type: "indirect",
      description: "Co-working space with an included coffee bar and day passes.",
      price_tier: "premium", target_audience: "Remote workers, freelancers", usp: "Guaranteed desks, meeting rooms, unlimited coffee",
      rating: 4.8, review_count: "~210 Google reviews",
      strengths: ["Purpose-built for work", "Community events", "Bookable meeting rooms"],
      weaknesses: ["$25+ day pass", "Downtown only", "Coffee is secondary"],
      marketing_channels: ["LinkedIn", "Meetup", "Google Ads"],
      scores: { pricing_value: 5, product_quality: 6, brand_strength: 6, digital_presence: 7, customer_experience: 8, innovation: 7 },
      threat_level: "low", threat_reason: "Targets the same remote-worker segment but at a much higher price point.",
    },
  ],
  market: {
    overview: "Austin's specialty coffee demand keeps growing with population and remote work, but the market is saturated in central neighborhoods. Differentiation is shifting from coffee quality alone to experience, convenience and community.",
    trends: ["Remote and hybrid workers using cafes as daytime offices", "Growth in cold brew and non-dairy drinks", "Mobile ordering expected by under-35s", "Consumers favouring local and sustainable brands"],
    customer_segments: ["Remote workers (weekday 9-4)", "Commuters (6-9am)", "Weekend brunch groups", "Students"],
    market_gaps: ["No East Austin cafe markets itself as work-friendly", "No local rival runs a digital loyalty program", "Few coffee tasting or roasting classes locally"],
  },
  swot: {
    strengths: ["Top-rated coffee quality", "Work-friendly space", "Authentic roasting story"],
    weaknesses: ["Low social media output", "No loyalty/mobile ordering", "Small marketing budget"],
    opportunities: ["Own the 'work-friendly cafe' positioning", "Sell beans online and via subscriptions", "Host cupping classes and community events"],
    threats: ["Lone Star opening a fourth location nearby", "Rising bean and rent costs", "Chain loyalty apps locking in commuters"],
  },
  recommendations: [
    { title: "Claim the 'best cafe to work from in East Austin' position", detail: "Add 'Work-friendly: fast Wi-Fi, outlets, quiet zone' to Google Business Profile, website and signage. Offer a $12 'Work Day' bundle (2 drinks + pastry).", priority: "high", timeframe: "0-30 days", channel: "Local SEO / Positioning", counters: "Daily Grind Cafe" },
    { title: "Launch a digital loyalty program", detail: "Use a low-cost loyalty app (buy 9 get 1) with SMS opt-in to compete with chain rewards and capture customer data.", priority: "high", timeframe: "1-3 months", channel: "Retention", counters: "Starline Coffee Co." },
    { title: "Post 4x a week on Instagram around the roasting story", detail: "Short Reels of roasting, latte art and regulars working. Tag local creators; run one giveaway a month.", priority: "medium", timeframe: "0-30 days", channel: "Instagram", counters: "Lone Star Roasters" },
    { title: "Monthly cupping classes", detail: "Ticketed $20 tasting sessions build community and PR, and upsell bean bags.", priority: "medium", timeframe: "1-3 months", channel: "Events / Community", counters: null },
    { title: "Online bean subscriptions", detail: "Sell 2-4 roasts via a simple Shopify store with local delivery, creating recurring revenue.", priority: "low", timeframe: "3-6 months", channel: "E-commerce", counters: "Lone Star Roasters" },
  ],
  keyword_opportunities: ["coffee shop to work east austin", "cafe with wifi austin", "best latte east austin", "local coffee roaster austin", "coffee near me open now"],
  sources: [
    { title: "Sample source (demo data)", url: "https://example.com" },
  ],
};
